name: static_analysis

on: [push]

jobs:
  phpstan_src:
    name: Phpstan_src
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project v2
        uses: actions/checkout@v2
            
      # composer-installer-action
      - uses: actions/checkout@master
      - uses: nanasess/composer-installer-action@master
      - run: composer install
      - run: php -d memory_limit=-1

      - name: PHPStan
        uses: docker://oskarstark/phpstan-ga
        env:
          REQUIRE_DEV: true
        with:
          args: analyze --configuration phpstan-ci-src.neon
